#!/bin/bash
default=origin

remote=${1:-origin}
for brname in `
  git branch -r | grep $remote | grep -v master | grep -v HEAD \
    | awk '{gsub(/[^\/]+\//,"",$1); print $1}'
  `; do 
  git branch --set-upstream $brname  $remote/$brname ; 
done
